# create product

POST http://localhost:3000/productapi/product
Content-Type: application/json

{
    "name":"tv","price":10000,"brand":"lg"
}



### get all products
GET http://localhost:3000/productapi/product


# create user

### 
POST http://localhost:3000/userapi/user 
Content-Type: application/json

{
    "name":"vilokg","email":"vgghk@gmail.com","password":"","cart":[]
}



### add items to cart
PUT http://localhost:3000/userapi/usercart/user-id/69807219bca22b441e4b77bf/product-id/698191dd60d597d6f4adfe5a



### read user by id
GET  http://localhost:3000/userapi/user/69807219bca22b441e4b77bf



### remove items from cart
DELETE  http://localhost:3000/userapi/usercart/user-id/69807219bca22b441e4b77bf/product-id/69806ab033c5a5eb2b1883a9
